### ISSUE TITLE
Progress bars are not displayed for catnip, titanium and science

### ISSUE THREAD

**Issue by kainers1** [vl20100/KGProgressBars#8]
Progress bars are not displayed for catnip, titanium and science

![image](https://github.com/vl20100/KGProgressBars/assets/1647619/c67efa4e-fabd-44b1-bad8-fceafb4d4b9d)

**Comment by vl20100** [comment]
The bug is not reproduced.
Can you tell us wich browser you are using and the version please ?
Do you use a specific theme ?

**Comment by kainers1** [comment]
Firefox 116 for Alpine Linux in a docker-container (https://hub.docker.com/r/jlesage/firefox).
It works fine with firefox on Windows.

Theme is 'inverted'

**Comment by kainers1** [comment]
I found out today that it has to do with the browser's zoom function; Firefox then simply doesn't display some bars. Sorry for the inconvenience.
